// ***********************************************************************
// Assembly         : KsWare.SignatureGenerator
// Author           : SchreinerK
// Created          : 03-26-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="BaseSignatureGenerator.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace KsWare.SignatureGenerator.Generators {

	/// <summary>
	/// Class BaseSignatureGenerator.
	/// </summary>
	/// <autogeneratedoc />
	public class BaseSignatureGenerator {

		/// <summary>
		/// Initializes a new instance of the <see cref="BaseSignatureGenerator"/> class.
		/// </summary>
		/// <param name="signatureHelper">The signature helper.</param>
		/// <autogeneratedoc />
		protected BaseSignatureGenerator(SignatureHelper signatureHelper) { SignatureHelper = signatureHelper; }

		/// <summary>
		/// Gets the signature helper.
		/// </summary>
		/// <value>The signature helper.</value>
		/// <autogeneratedoc />
		protected SignatureHelper SignatureHelper { get; }

		/// <summary>
		/// Gets the signature mode.
		/// </summary>
		/// <value>The signature mode.</value>
		/// <autogeneratedoc />
		public SignatureMode SignatureMode => SignatureHelper.SignatureMode;
	}

}