// ***********************************************************************
// Assembly         : KsWare.SignatureGenerator
// Author           : SchreinerK
// Created          : 2018-03-12
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="SignatureHelper.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************


namespace KsWare.SignatureGenerator.Generators {

	/// <summary>
	/// Class EventSignatureOptions.
	/// </summary>
	/// <autogeneratedoc />
	public class EventSignatureOptions {

		/// <summary>
		/// Creates the options for the specified signature mode.
		/// </summary>
		/// <param name="signatureMode">The signature mode.</param>
		/// <returns>EventSignatureOptions.</returns>
		public static EventSignatureOptions Create(SignatureMode signatureMode) {
			return new EventSignatureOptions { };
		}
	}
}
