namespace KsWare.SignatureGenerator.Generators {

	/// <summary>
	/// Class FieldSignatureOptions.
	/// </summary>
	/// <autogeneratedoc />
	public class FieldSignatureOptions {

		/// <summary>
		/// Creates the options for the specified signature mode.
		/// </summary>
		/// <param name="signatureMode">The signature mode.</param>
		/// <returns>FieldSignatureOptions.</returns>
		public static FieldSignatureOptions Create(SignatureMode signatureMode) {
			return new FieldSignatureOptions { };
		}
	}

}