// ***********************************************************************
// Assembly         : KsWare.SignatureGenerator
// Author           : SchreinerK
// Created          : 03-27-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="GenericParameterSignatureOptions.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace KsWare.SignatureGenerator.Generators {

	/// <summary>
	/// Class GenericParameterSignatureOptions.
	/// </summary>
	/// <autogeneratedoc />
	public class GenericParameterSignatureOptions {
		/// <summary>
		/// Gets or sets a value indicating whether the name is included.
		/// </summary>
		/// <value><c>true</c> if name is included; otherwise, <c>false</c>.</value>
		public bool Name { get; set; }

		/// <summary>
		/// Creates the options for the specified signature mode.
		/// </summary>
		/// <param name="signatureMode">The signature mode.</param>
		/// <returns><see cref="ParameterSignatureOptions"/>.</returns>
		public static ParameterSignatureOptions Create(SignatureMode signatureMode) {
			switch (signatureMode) {
				case SignatureMode.CompareIgnoreReturnType:
				case SignatureMode.Compare: return new ParameterSignatureOptions {Name = false};
				default: return new ParameterSignatureOptions {Name = true};
			}
		}
	}

}