// ***********************************************************************
// Assembly         : KsWare.SignatureGenerator
// Author           : SchreinerK
// Created          : 03-27-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="ParameterSignatureOptions.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

using System.Collections.Generic;

namespace KsWare.SignatureGenerator.Generators {

	/// <summary>
	/// Class ParameterSignatureOptions.
	/// </summary>
	/// <autogeneratedoc />
	public class ParameterSignatureOptions {

		private const bool X = true;
		private const bool ˑ = false;
		private static Dictionary<SignatureMode, bool[]> matrix = new Dictionary<SignatureMode, bool[]> {
			/*                                             Modifiers                     */
			/*                                             |  Type                       */
			/*                                             |  |  Name                    */
			{SignatureMode.Code                   , new[] {X, X, X}},
			{SignatureMode.Compare                , new[] {X, X, ˑ}},
			{SignatureMode.CompareIgnoreReturnType, new[] {X, X, X}},
			{SignatureMode.InheriteDoc            , new[] {ˑ, X, ˑ}},
			{SignatureMode.Signature              , new[] {X, X, ˑ}}, // modifiers "ref", "out", but not "params"
			{SignatureMode.Call                   , new[] {ˑ, ˑ, X}},
			{SignatureMode.Declare                , new[] {X, X, X}},
		};

		/// <summary>
		/// Gets or sets a value indicating whether modifiers (<c>ref</c>, <c>out</c>, <c>params</c>) are included.
		/// </summary>
		/// <value><c>true</c> if modifiers are included; otherwise, <c>false</c>.</value>
		/// <autogeneratedoc />
		public bool Modifiers { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether type is included.
		/// </summary>
		/// <value><c>true</c> if type is included; otherwise, <c>false</c>.</value>
		public bool Type { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether name is included.
		/// </summary>
		/// <value><c>true</c> if name is included; otherwise, <c>false</c>.</value>
		public bool Name { get; set; }

		/// <summary>
		/// Creates the options for the specified signature mode.
		/// </summary>
		/// <param name="signatureMode">The signature mode.</param>
		/// <returns>ParameterSignatureOptions.</returns>
		/// <autogeneratedoc />
		public static ParameterSignatureOptions Create(SignatureMode signatureMode) {
			var m = matrix[signatureMode];
			return new ParameterSignatureOptions {
				Modifiers = m[0],
				Type      = m[1],
				Name      = m[2],
			};
		}
	}

}