// ***********************************************************************
// Assembly         : KsWare.SignatureGenerator
// Author           : SchreinerK
// Created          : 03-26-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="ParameterSignatureGenerator.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

using System;
using System.Linq;
using System.Reflection;
using System.Text;

namespace KsWare.SignatureGenerator.Generators {

	/// <summary>
	/// Class ParameterSignatureGenerator.
	/// </summary>
	/// <seealso cref="KsWare.SignatureGenerator.Generators.BaseSignatureGenerator" />
	/// <autogeneratedoc />
	public class ParameterSignatureGenerator : BaseSignatureGenerator {
		// Modifier Type Name  default
		//          T    name  = value
		// out      T    name  
		// ref      T    name
		// params  T[]   name

		/// <summary>
		/// Initializes a new instance of the <see cref="ParameterSignatureGenerator"/> class.
		/// </summary>
		/// <param name="signatureHelper">The signature helper.</param>
		/// <autogeneratedoc />
		public ParameterSignatureGenerator(SignatureHelper signatureHelper) : base(signatureHelper) { }

		/// <summary>
		/// Creates signature for the specified parameter information.
		/// </summary>
		/// <param name="parameterInfo">The parameter information.</param>
		/// <returns>System.String.</returns>
		public string Sig(ParameterInfo parameterInfo) => Sig(parameterInfo, ParameterSignatureOptions.Create(SignatureMode));

		/// <summary>
		/// Creates signature for the specified parameter information.
		/// </summary>
		/// <param name="parameterInfo">The parameter information.</param>
		/// <param name="options">The signature options.</param>
		/// <returns>System.String.</returns>
		public string Sig(ParameterInfo parameterInfo, ParameterSignatureOptions options) {
			var sb = new StringBuilder();
			//Attributes?

//			parameterInfo.IsIn;
//			parameterInfo.IsOut;
//			parameterInfo.IsRetval;
//			parameterInfo.IsLcid;
//			parameterInfo.HasDefaultValue;
//TODO		parameterInfo.DefaultValue;
//			parameterInfo.RawDefaultValue;
//			parameterInfo.IsOptional;

			var isParams = parameterInfo.GetCustomAttributes(typeof(ParamArrayAttribute)).Any();

			var type = SignatureHelper.Sig(parameterInfo.ParameterType) + " ";
			var modifier = type.StartsWith("ref ") ? "ref " : "";
			if (parameterInfo.IsOut) modifier = "out ";
			if (type.StartsWith("ref ")) type = type.Substring(4);
			if (isParams) modifier = "params ";

			// "params" is not relevant for signature 
			if (isParams && SignatureMode == SignatureMode.Signature) modifier = "";

			if (options.Modifiers) sb.Append(modifier);
			if (options.Type) sb.Append(type);
			if (options.Name) sb.Append(parameterInfo.Name);

			return sb.ToString().Trim();
		}

		
	}
}
