// ***********************************************************************
// Assembly         : KsWare.SignatureGenerator
// Author           : SchreinerK
// Created          : 03-27-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="PropertySignatureOptions.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace KsWare.SignatureGenerator.Generators {

	/// <summary>
	/// Class PropertySignatureOptions.
	/// </summary>
	/// <autogeneratedoc />
	public class PropertySignatureOptions {

		/// <summary>
		/// Creates the options for the specified signature mode.
		/// </summary>
		/// <param name="signatureMode">The signature mode.</param>
		/// <returns>PropertySignatureOptions.</returns>
		public static PropertySignatureOptions Create(SignatureMode signatureMode) {
			return new PropertySignatureOptions{};
		}
	}

}