// ***********************************************************************
// Assembly         : KsWare.SignatureGenerator
// Author           : SchreinerK
// Created          : 03-26-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="BaseGenerator.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace KsWare.CodeGenerator.Generators {

	/// <summary>
	/// Class BaseGenerator.
	/// </summary>
	/// <autogeneratedoc />
	public class BaseGenerator {

		/// <summary>
		/// Initializes a new instance of the <see cref="BaseGenerator"/> class.
		/// </summary>
		/// <param name="generator">The generator.</param>
		/// <autogeneratedoc />
		protected BaseGenerator(Generator generator) { Generator = generator; }

		/// <summary>
		/// Gets the generator.
		/// </summary>
		/// <value>The generator.</value>
		/// <autogeneratedoc />
		protected Generator Generator { get; }

		/// <summary>
		/// Gets the generator mode.
		/// </summary>
		/// <value>The generator mode.</value>
		/// <autogeneratedoc />
		public GeneratorMode GeneratorMode => Generator.GeneratorMode;
	}

}