// ***********************************************************************
// Assembly         : KsWare.CodeGenerator
// Author           : SchreinerK
// Created          : 2018-03-12
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="SignatureHelper.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************


namespace KsWare.CodeGenerator.Generators {

	/// <summary>
	/// Class EventGeneratorOptions.
	/// </summary>
	/// <autogeneratedoc />
	public class EventGeneratorOptions {

		/// <summary>
		/// Creates the options for the specified generator mode.
		/// </summary>
		/// <param name="generatorMode">The generator mode.</param>
		/// <returns>EventGeneratorOptions.</returns>
		public static EventGeneratorOptions Create(GeneratorMode generatorMode) {
			return new EventGeneratorOptions { };
		}
	}
}
