// ***********************************************************************
// Assembly         : KsWare.CodeGenerator
// Author           : SchreinerK
// Created          : 03-26-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="EventGenerator.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System.Reflection;
using System.Text;

namespace KsWare.CodeGenerator.Generators {

	/// <summary>
	/// Class EventGenerator.
	/// </summary>
	/// <seealso cref="BaseGenerator" />
	/// <autogeneratedoc />
	public class EventGenerator : BaseGenerator {


		/// <summary>
		/// Initializes a new instance of the <see cref="EventGenerator"/> class.
		/// </summary>
		/// <param name="generator">The generator.</param>
		/// <autogeneratedoc />
		public EventGenerator(Generator generator) : base(generator) { }


		/// <summary>
		/// Generates code for the specified event information.
		/// </summary>
		/// <param name="eventInfo">The event information.</param>
		/// <returns>System.String.</returns>
		public string Generate(EventInfo eventInfo) => Generate(eventInfo, EventGeneratorOptions.Create(GeneratorMode));

		/// <summary>
		/// Generates code for the specified event information.
		/// </summary>
		/// <param name="eventInfo">The event information.</param>
		/// <param name="options">The generator options.</param>
		/// <returns>System.String.</returns>
		public string Generate(EventInfo eventInfo, EventGeneratorOptions options) {
			var sb = new StringBuilder();
			var mi = eventInfo.AddMethod; // TODO

			sb.Append($"{Generator.Generate(mi.Attributes)}");
			sb.Append("event ");
			sb.Append($"{eventInfo.EventHandlerType} ");
			sb.Append($"{eventInfo.Name}");

			return sb.ToString();
		}
	}
}
