// ***********************************************************************
// Assembly         : KsWare.SignatureGenerator
// Author           : SchreinerK
// Created          : 03-27-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="GenericParameterGeneratorOptions.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace KsWare.CodeGenerator.Generators {

	/// <summary>
	/// Class GenericParameterGeneratorOptions.
	/// </summary>
	/// <autogeneratedoc />
	public class GenericParameterGeneratorOptions {
		/// <summary>
		/// Gets or sets a value indicating whether the name is included.
		/// </summary>
		/// <value><c>true</c> if name is included; otherwise, <c>false</c>.</value>
		public bool Name { get; set; }

		/// <summary>
		/// Creates the options for the specified generator mode.
		/// </summary>
		/// <param name="generatorMode">The generator mode.</param>
		/// <returns><see cref="ParameterGeneratorOptions"/>.</returns>
		public static ParameterGeneratorOptions Create(GeneratorMode generatorMode) {
			switch (generatorMode) {
				case GeneratorMode.CompareIgnoreReturnType:
				case GeneratorMode.Compare: return new ParameterGeneratorOptions {Name = false};
				default: return new ParameterGeneratorOptions {Name = true};
			}
		}
	}

}