// ***********************************************************************
// Assembly         : KsWare.CodeGenerator
// Author           : SchreinerK
// Created          : 03-27-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="PropertyGeneratorOptions.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

using System.Collections.Generic;

namespace KsWare.CodeGenerator.Generators {

	/// <summary>
	/// Class PropertyGeneratorOptions.
	/// </summary>
	/// <autogeneratedoc />
	public class PropertyGeneratorOptions {

		private const bool X = true;
		private const bool o = false;
		private static Dictionary<GeneratorMode, bool[]> matrix = new Dictionary<GeneratorMode, bool[]> {
			/*                                             Access                               */
			/*                                             |  Modifiers                         */
			/*                                             |  |  Type                           */
			/*                                             |  |  |  Name                        */
			{GeneratorMode.Code                   , new[] {X, X, X, X}},
			{GeneratorMode.Compare                , new[] {X, X, X, X}},
			{GeneratorMode.CompareIgnoreReturnType, new[] {X, X, o, X}},
			{GeneratorMode.InheriteDoc            , new[] {o, o, o, X}},
			{GeneratorMode.Signature              , new[] {o, o, o, X}},
			{GeneratorMode.Call                   , new[] {o, o, o, X}},
			{GeneratorMode.Declare                , new[] {X, X, X, X}},
		};

		/// <summary>
		/// Gets or sets a value indicating whether access is included.
		/// </summary>
		/// <value><c>true</c> if access is included; otherwise, <c>false</c>.</value>
		public bool Access { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether this modifiers are included.
		/// </summary>
		/// <value><c>true</c> if modifiers are included; otherwise, <c>false</c>.</value>
		/// <autogeneratedoc />
		public bool Modifiers { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether type is included.
		/// </summary>
		/// <value><c>true</c> if type is included; otherwise, <c>false</c>.</value>
		public bool Type { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether name is included.
		/// </summary>
		/// <value><c>true</c> if name is included; otherwise, <c>false</c>.</value>
		public bool Name { get; set; }

		/// <summary>
		/// Creates the options for the specified generator mode.
		/// </summary>
		/// <param name="generatorMode">The generator mode.</param>
		/// <returns>FieldGeneratorOptions.</returns>
		/// <autogeneratedoc />
		public static PropertyGeneratorOptions Create(GeneratorMode generatorMode) {
			var m = matrix[generatorMode];
			return new PropertyGeneratorOptions {
				Access     = m[0],
				Modifiers  = m[1],
				Type       = m[2],
				Name       = m[3],
			};
		}
	}

}