// ***********************************************************************
// Assembly         : KsWare.SignatureGenerator
// Author           : SchreinerK
// Created          : 03-26-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="PropertyGenerator.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
using System.Reflection;
using System.Text;

namespace KsWare.CodeGenerator.Generators {

	/// <summary>
	/// Class PropertyGenerator.
	/// </summary>
	/// <seealso cref="BaseGenerator" />
	/// <autogeneratedoc />
	public class PropertyGenerator : BaseGenerator {

		/// <summary>
		/// Initializes a new instance of the <see cref="PropertyGenerator"/> class.
		/// </summary>
		/// <param name="generator">The generator.</param>
		/// <autogeneratedoc />
		public PropertyGenerator(Generator generator) : base(generator) { }

		/// <summary>
		/// Generates code for the specified property information.
		/// </summary>
		/// <param name="propertyInfo">The property information.</param>
		/// <returns>System.String.</returns>
		public string Generate(PropertyInfo propertyInfo) => Generate(propertyInfo, PropertyGeneratorOptions.Create(GeneratorMode));

		/// <summary>
		/// Generates code for the specified property information.
		/// </summary>
		/// <param name="propertyInfo">The property information.</param>
		/// <param name="options">The generator options.</param>
		/// <returns>System.String.</returns>
		public string Generate(PropertyInfo propertyInfo, PropertyGeneratorOptions options) {
			var sb     = new StringBuilder();
			var getter = propertyInfo.GetMethod;
			var setter = propertyInfo.SetMethod;

			string access = "";
			if (getter != null && setter != null) {
				var getterAccess = Generator.SigAccess(getter.Attributes);
				var setterAccess = Generator.SigAccess(setter.Attributes);
				access = Generator.MaxAccess(getterAccess, setterAccess) + " ";
			}
			else if (getter != null) {
				access = Generator.SigAccess(getter.Attributes);
			}
			else if (setter != null) {
				access = Generator.SigAccess(setter.Attributes);
			}

			var mi = getter ?? setter;

			sb.Append(access);
			sb.Append(Generator.SigModifier(mi.Attributes));

			sb.Append(Generator.Generate(propertyInfo.PropertyType));
			sb.Append(" ");
			if (propertyInfo.Name == "Item" && propertyInfo.GetMethod.GetParameters().Length > 0) {
				sb.Append("this[");
				sb.Append(Generator.Generate(propertyInfo.GetMethod.GetParameters()));
				sb.Append("]");
			}
			else {
				sb.Append(propertyInfo.Name);
			}

			sb.Append(" { ");

			if (propertyInfo.CanRead) {
				var getterAccess = Generator.SigAccess(getter.Attributes);
				if (getterAccess != access) sb.Append(getterAccess);
				sb.Append("get; ");
			}
			if (propertyInfo.CanWrite) {
				var setterAccess = Generator.SigAccess(setter.Attributes);
				if (setterAccess != access) sb.Append(setterAccess);
				sb.Append("set; ");
			}
			sb.Append("}");

			return sb.ToString();
		}
	}
}
