// ***********************************************************************
// Assembly         : KsWare.SignatureGenerator
// Author           : SchreinerK
// Created          : 03-27-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-27-2018
// ***********************************************************************
// <copyright file="TypeNameGeneratorOptions.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************
namespace KsWare.CodeGenerator.Generators {

	/// <summary>
	/// Class TypeNameGeneratorOptions.
	/// </summary>
	/// <autogeneratedoc />
	public class TypeNameGeneratorOptions {

		/// <summary>
		/// Gets or sets a value indicating whether access is included.
		/// </summary>
		/// <value><c>true</c> if access is included; otherwise, <c>false</c>.</value>
		public bool Access { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether this modifiers are included.
		/// </summary>
		/// <value><c>true</c> if modifiers are included; otherwise, <c>false</c>.</value>
		public bool Modifiers { get; set; }

		/// <summary>
		/// Gets or sets a value indicating whether name is included.
		/// </summary>
		/// <value><c>true</c> if name is included; otherwise, <c>false</c>.</value>
		public bool Name { get; set; }

		/// <summary>
		/// Creates the options for the specified generator mode.
		/// </summary>
		/// <param name="generatorMode">The mode.</param>
		/// <returns>TypeNameGeneratorOptions.</returns>
		/// <autogeneratedoc />
		public static TypeNameGeneratorOptions Create(GeneratorMode generatorMode) {
			return new TypeNameGeneratorOptions{Access = true, Modifiers = true, Name = true};
		}
	}

}