// ***********************************************************************
// Assembly         : KsWare.CodeGenerator
// Author           : SchreinerK
// Created          : 03-25-2018
//
// Last Modified By : SchreinerK
// Last Modified On : 03-28-2018
// ***********************************************************************
// <copyright file="GeneratorMode.cs" company="KsWare">
//     Copyright © 2018 KsWare. All rights reserved.
// </copyright>
// <summary></summary>
// ***********************************************************************

using System;

namespace KsWare.CodeGenerator {

	/// <summary>
	/// Enum GeneratorMode
	/// </summary>
	/// <autogeneratedoc />
	public enum GeneratorMode {

		/// <summary>
		/// No mode specified.
		/// </summary>
		None,
		
		/// <summary>
		/// The signature mode.
		/// </summary>
		/// <autogeneratedoc />
		Signature,
		
		/// <summary>
		/// The compare mode.
		/// </summary>
		/// <autogeneratedoc />
		Compare,
		
		/// <summary>
		/// The code mode.
		/// </summary>
		[Obsolete("Use Declare|Call")]
		Code,
		
		/// <summary>
		/// The compare mode with ignore return type.
		/// </summary>
		/// <autogeneratedoc />
		CompareIgnoreReturnType,
		
		/// <summary>
		/// The inherite documentation mode.
		/// </summary>
		/// <autogeneratedoc />
		InheriteDoc,
		
		/// <summary>
		/// The call mode.
		/// </summary>
		/// <autogeneratedoc />
		Call,
		
		/// <summary>
		/// The declare mode.
		/// </summary>
		/// <autogeneratedoc />
		Declare
	}

}